name: Node.js CI

on:
  push:
    branches: [ build ]
  pull_request:
    branches: [ build ]
    
jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - run: npm install -f
    - run: npm run build
    - run: docker build -t email-api .
    - run: docker rm -f email-api
    - run: docker run --name email-api -e PORT=${{ secrets.PORT }} -e APP_SECRET=${{ secrets.APP_SECRET }} -e EMAIL_SERVER=${{ secrets.EMAIL_SERVER }} -e EMAIL_PORT=${{ secrets.EMAIL_PORT }} -e EMAIL_TLS=${{ secrets.EMAIL_TLS }} -e EMAIL_NAME=${{ secrets.EMAIL_NAME }} -e EMAIL=${{ secrets.EMAIL }} -e EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} --network host -d email-api
